/**
 * Closed Desktop-control protocol shared by Harness, Electron, and the native helper.
 * @module @deepseek-ai/dsh-desktop-control-protocol
 */

export {
  BrowserRef,
  ComputerRef,
  ControlLeaseId,
  PngTransferId,
  RequestId,
  SessionId,
} from './brand.ts'
export type {
  BrowserRef as BrowserRefType,
  ComputerRef as ComputerRefType,
  ControlLeaseId as ControlLeaseIdType,
  PngTransferId as PngTransferIdType,
  RequestId as RequestIdType,
  SessionId as SessionIdType,
} from './brand.ts'
export {
  BRIDGE_REQUEST_KINDS,
  CONTROL_LEASE_CAPABILITIES,
  CONTROL_LEASE_SURFACE_KINDS,
  CONTROL_KINDS,
  ERROR_CODES,
  PROTOCOL_VERSION,
} from './bridge.ts'
export type {
  ActionResult,
  BridgeRequest,
  BridgeRequestKind,
  BrowserClickRequest,
  BrowserKeyRequest,
  BrowserNavigateRequest,
  BrowserNavigationRequest,
  BrowserNavigationResult,
  BrowserScrollRequest,
  BrowserSelectRequest,
  BrowserSemanticRef,
  BrowserSnapshotRequest,
  BrowserSnapshotResult,
  BrowserStopRequest,
  BrowserTypeRequest,
  BrowserWaitRequest,
  ComputerClickRequest,
  ComputerDragRequest,
  ComputerFocusRequest,
  ComputerKeyRequest,
  ComputerListRequest,
  ComputerListResult,
  ComputerScrollRequest,
  ComputerSemanticRef,
  ComputerSnapshotRequest,
  ComputerSnapshotResult,
  ComputerStatusRequest,
  ComputerStatusResult,
  ComputerStopRequest,
  ComputerTypeRequest,
  ComputerWaitRequest,
  ControlLeaseAcquireRequest,
  ControlLeaseAcquireResult,
  ControlLeaseCapability,
  ControlLeaseReleaseRequest,
  ControlLeaseReleaseResult,
  ControlLeaseSurfaceKind,
  ControlLeaseTarget,
  ControlKind,
  DesktopControlControl,
  DesktopControlError,
  DesktopControlErrorCode,
  DesktopControlErrorResponse,
  DesktopControlOkResponse,
  DesktopControlResultMap,
  DesktopStatusRequest,
  DesktopStatusResult,
  GrantableApplication,
  KeyModifier,
  PngMetadata,
  PointerButton,
  StopResult,
  WaitResult,
} from './bridge.ts'
export { HELPER_REQUEST_KINDS } from './helper.ts'
export { CONTROL_LEASE_QUOTA_FIELDS, CONTROL_LEASE_TARGET_FIELDS } from './fields.ts'
export type {
  ControlLeaseQuotaSnapshot,
  HelperClickRequest,
  HelperDragRequest,
  HelperErrorResponse,
  HelperFocusRequest,
  HelperInputReleaseRequest,
  HelperInputReleaseResult,
  HelperKeyRequest,
  HelperLeaseInstallRequest,
  HelperLeaseInstallResult,
  HelperListRequest,
  HelperOkResponse,
  HelperRequest,
  HelperRequestKind,
  HelperResultMap,
  HelperScrollRequest,
  HelperSnapshotRequest,
  HelperStatusRequest,
  HelperStopRequest,
  HelperTypeRequest,
  HelperWaitRequest,
} from './helper.ts'
export { assertProtocolManifest, PROTOCOL_LIMITS, PROTOCOL_MANIFEST, validateProtocolManifest } from './manifest.ts'
export {
  assertBridgeDeadline,
  decodeJsonFrame,
  decodePngFrame,
  DesktopControlFrameDecoder,
  DesktopControlProtocolError,
  encodeJsonFrame,
  encodeLengthPrefixedFrame,
  encodePngFrame,
  ImmutablePng,
  LengthPrefixedFrameDecoder,
} from './codec.ts'
export type {
  DecodedDesktopControlEnvelope,
  DecodedPngFrame,
  DesktopControlMessage,
  DesktopControlMessageValidator,
} from './codec.ts'
